<script setup>
/*
 | Demo harness.
 |
 | Stands in for the Inertia page that will host the map inside
 | seniorsplaces-platform. It does exactly what that page will do: pass a
 | community payload in, and handle the `lead` event by posting it somewhere.
 | Here "somewhere" is a console log and a two-second fake round trip, so the
 | success state is reachable without a backend.
 |
 | The controls along the top exist to exercise cases that are otherwise hard
 | to reach: a community that keeps its rates private, and a community with a
 | single building. Both are real configurations on the platform today.
 */
import { computed, ref } from 'vue';
import CommunityMap from '../src/components/CommunityMap.vue';
import raw from './data/willow-creek.json';

const pricingPublic = ref(true);
const singleBuilding = ref(false);

const community = computed(() => ({
    ...raw,
    pricingPublic: pricingPublic.value,
    buildings: singleBuilding.value ? raw.buildings.slice(0, 1) : raw.buildings,
}));

const submitting = ref(false);
const sent = ref(false);
const error = ref(null);
const lastLead = ref(null);

async function onLead(payload) {
    lastLead.value = payload;
    submitting.value = true;
    error.value = null;
    console.log('[demo] lead payload that would POST to /api/leads:', payload);

    await new Promise((r) => setTimeout(r, 900));
    submitting.value = false;
    sent.value = true;
    setTimeout(() => { sent.value = false; }, 6000);
}
</script>

<template>
    <div class="min-h-dvh bg-warm-2 font-sans text-ink">
        <div class="mx-auto max-w-[1280px] px-4 py-6 sm:px-6">
            <header class="mb-5">
                <p class="text-[11px] font-bold uppercase tracking-[1.4px] text-ink-light">Seniors Places · component demo</p>
                <h1 class="mt-1 font-serif text-[30px] font-bold leading-tight sm:text-[36px]">Community map</h1>
                <p class="mt-1.5 max-w-[62ch] text-[15px] leading-relaxed text-ink-mid">
                    A replacement for the embedded SightMap on a client listing. Real unit geometry, senior-living
                    availability states, care-level pricing worked out in front of the family, full keyboard operation,
                    and a URL for every suite.
                </p>

                <div class="mt-4 flex flex-wrap gap-4 rounded-card border border-hairline bg-white px-4 py-3">
                    <label class="flex cursor-pointer items-center gap-2 text-[13.5px]">
                        <input v-model="pricingPublic" type="checkbox" class="size-4 rounded accent-[var(--color-brand)]" />
                        Publish rates <span class="text-ink-light">(off = “pricing on request” listing)</span>
                    </label>
                    <label class="flex cursor-pointer items-center gap-2 text-[13.5px]">
                        <input v-model="singleBuilding" type="checkbox" class="size-4 rounded accent-[var(--color-brand)]" />
                        Single building <span class="text-ink-light">(hides the building switcher)</span>
                    </label>
                </div>
            </header>

            <CommunityMap
                :key="`${pricingPublic}-${singleBuilding}`"
                :community="community"
                :submitting="submitting"
                :lead-sent="sent"
                :lead-error="error"
                @lead="onLead"
            />

            <section v-if="lastLead" class="mt-5 rounded-card border border-hairline bg-white p-4">
                <h2 class="font-serif text-[17px] font-bold">Last lead payload</h2>
                <p class="mt-0.5 text-[13px] text-ink-mid">
                    This is the object emitted to the host app. In the platform it maps onto the existing
                    <code class="rounded bg-warm px-1">leads</code> table — see docs/INTEGRATION.md.
                </p>
                <pre class="mt-2 max-h-[280px] overflow-auto rounded-brand bg-warm p-3 text-[12px] leading-relaxed">{{ JSON.stringify(lastLead, null, 2) }}</pre>
            </section>

            <footer class="mt-6 text-[12.5px] text-ink-light">
                Willow Creek is a synthetic community generated by
                <code class="rounded bg-white px-1">scripts/build-demo.mjs</code>. No real availability or rates.
            </footer>
        </div>
    </div>
</template>
